export const typeColors = {
  // fire: "bg-red-500 text-white",
  // water: "bg-blue-500 text-white",
  // grass: "bg-green-500 text-white",
  // electric: "bg-yellow-400 text-black",
  // psychic: "bg-pink-500 text-white",
  // ice: "bg-cyan-300 text-black",
  // dragon: "bg-purple-600 text-white",
  // dark: "bg-gray-800 text-white",
  // fairy: "bg-pink-300 text-black",
  // fighting: "bg-orange-600 text-white",
  // flying: "bg-indigo-300 text-black",
  // poison: "bg-violet-500 text-white",
  // ground: "bg-amber-600 text-white",
  // rock: "bg-stone-600 text-white",
  // bug: "bg-lime-400 text-black",
  // ghost: "bg-indigo-700 text-white",
  // steel: "bg-gray-400 text-black",
  // normal: "bg-gray-200 text-black",

  fire: "bg-red-500 text-white",
  water: "bg-blue-500 text-white",
  grass: "bg-green-500 text-white",
  electric: "bg-yellow-400 text-black",
};
